# This file configures the analyzer to reduce false positives
# include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    # Ignore specific error types
    undefined_class: ignore
    undefined_identifier: ignore
    undefined_method: ignore
    undefined_getter: ignore
    undefined_setter: ignore
    uri_does_not_exist: ignore
    uri_has_not_been_generated: ignore
    undefined_annotation: ignore
    non_type_as_type_argument: ignore
    creation_with_non_type: ignore
    extends_non_class: ignore
    mixin_of_non_class: ignore
    implements_non_class: ignore
    constant_pattern_with_non_constant_expression: ignore
    
    # Treat as warnings instead of errors
    missing_required_param: warning
    missing_return: warning
    
    # Ignore deprecated member use in generated files
    deprecated_member_use_from_same_package: ignore
    
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "build/**"
    - "**/.dart_tool/**"
    - "**/generated/**"

linter:
  rules:
    # Disable some overly strict rules
    prefer_const_constructors: false
    prefer_const_declarations: false
    prefer_const_literals_to_create_immutables: false
    avoid_print: false
    use_key_in_widget_constructors: false
    prefer_final_fields: false
    unnecessary_const: false
    unnecessary_new: false
    constant_identifier_names: false
