name: nokta_saas
packages:
  - packages/**
  - apps/**

scripts:
  analyze:
    run: flutter analyze
    exec:
      concurrency: 1
  test:
    run: flutter test
    exec:
      concurrency: 1
  build:all:
    run: melos exec -- "flutter build"
