name: pos_app
description: Point of Sale Application for Nokta POS System
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # Core Package
  nokta_core:
    path: ../../packages/core
    
  # State Management
  flutter_riverpod: ^2.4.9
  
  # Navigation
  go_router: ^12.1.3
  
  # Database
  sqflite: ^2.3.0
  path: ^1.8.3
  
  # Network
  dio: ^5.4.0
  connectivity_plus: ^5.0.2
  
  # Storage
  shared_preferences: ^2.2.2
  
  # Printing
  printing: ^5.11.1
  pdf: ^3.11.2
  
  # Barcode/QR
  mobile_scanner: ^3.5.5
  qr_flutter: ^4.1.0
  
  # UI Components
  data_table_2: ^2.5.9
  fl_chart: ^0.65.0
  
  # Utilities - Fixed intl version
  intl: ^0.20.2  # Updated to match flutter_localizations
  collection: ^1.18.0
  
  # Icons
  cupertino_icons: ^1.0.6
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/sounds/
  
  # fonts:
  #   - family: Cairo
  #     fonts:
  #       - asset: assets/fonts/Cairo-Regular.ttf
  #       - asset: assets/fonts/Cairo-Bold.ttf
  #         weight: 700
